name: "Publish to FlakeHub"
on:
  push:
    branches:
      - main
    tags:
      - "*"
jobs:
  flakehub-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v7
      - uses: DeterminateSystems/determinate-nix-action@v3
      - uses: DeterminateSystems/flakehub-push@4752651a220bf6431efb035bd50c002ead02507e
        with:
          rolling: true
          visibility: public
          include-output-paths: true
